/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package convertidor;

import javax.swing.JOptionPane;

/**
 *
 * @author gemin_7bxj2ds
 */
public class ConvertidorMonedas extends javax.swing.JInternalFrame {

    private static double moneda;
    private static double monto;
    private static double result;
    String money;
    String money1;

    public ConvertidorMonedas() {
        initComponents();
        this.setSize(389, 321);
        this.setVisible(true);
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxConvertir_A = new javax.swing.JComboBox<>();
        txtConvertido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbxConvertir_De = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setText("CONVERTIDOR DE MONEDAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel2.setText("CONVERTIR A :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel4.setText("CONVERTIR DE :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        cbxConvertir_A.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        cbxConvertir_A.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soles", "Dolar", "Euro", "Libra Esterlina", "Yen Japones", "Won Sur Coreano" }));
        cbxConvertir_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxConvertir_AActionPerformed(evt);
            }
        });
        getContentPane().add(cbxConvertir_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 143, -1));

        txtConvertido.setEditable(false);
        txtConvertido.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        getContentPane().add(txtConvertido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 143, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel5.setText("MONTO CONVERTIDO :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        cbxConvertir_De.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        cbxConvertir_De.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soles", "Dolar", "Euro", "Libra Esterlina", "Yen Japones", "Won Sur Coreano" }));
        cbxConvertir_De.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxConvertir_DeActionPerformed(evt);
            }
        });
        getContentPane().add(cbxConvertir_De, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 143, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel3.setText("MONTO :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        txtMonto.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        getContentPane().add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 143, -1));

        btnConvertir.setBackground(new java.awt.Color(0, 0, 255));
        btnConvertir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/money.png"))); // NOI18N
        btnConvertir.setText("Convertir");
        btnConvertir.setBorder(null);
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });
        getContentPane().add(btnConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 228, 150, 50));

        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 228, 150, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 400, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxConvertir_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxConvertir_AActionPerformed

        money1 = cbxConvertir_A.getSelectedItem().toString();
        ConvertirA(money1);

    }//GEN-LAST:event_cbxConvertir_AActionPerformed

    private void cbxConvertir_DeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxConvertir_DeActionPerformed

        money = cbxConvertir_De.getSelectedItem().toString();
        ConvertirDe(money);

    }//GEN-LAST:event_cbxConvertir_DeActionPerformed

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed

        String valor = txtMonto.getText();
        if ("".equals(valor)) {
            JOptionPane.showMessageDialog(rootPane, "Se debe ingresar un valor.");
        } else {
            String vacio = null;
            if ((vacio == null ? money1 != null : !vacio.equals(money1))
                    && (vacio == null ? money != null : !vacio.equals(money))) {
                double conver = Math.round(result * 1000.0) / 1000.0;
                txtConvertido.setText(String.valueOf(conver));

            } else {
                JOptionPane.showMessageDialog(rootPane, "Debe seleccionar ambos tipos de cambio");
            }

        }
    }//GEN-LAST:event_btnConvertirActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxConvertir_A;
    private javax.swing.JComboBox<String> cbxConvertir_De;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtConvertido;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables

    private void ConvertirDe(String money) {
        if (!"".equals(money)) {
            double mont = Double.parseDouble(txtMonto.getText());
            switch (money) {
                case "Soles":
                    moneda = 1.0;
                    monto = mont / moneda;
                    break;
                case "Dolar":
                    moneda = 0.2753;
                    monto = mont / moneda;
                    break;
                case "Euro":
                    moneda = 0.2535;
                    monto = mont / moneda;
                    break;
                case "Libra Esterlina":
                    moneda = 0.2167;
                    monto = mont / moneda;
                    break;
                case "Yen Japones":
                    moneda = 39.8045;
                    monto = mont / moneda;
                    break;
                case "Won Sur Coreano":
                    moneda = 0.0028;
                    monto = mont / moneda;
                    break;
            }
        }
    }

    private void ConvertirA(String money) {
        if (!"".equals(money)) {
            switch (money) {
                case "Soles":
                    moneda = 1.0;
                    result = monto * moneda;
                    break;
                case "Dolar":
                    moneda = 0.2753;
                    result = monto * moneda;
                    break;
                case "Euro":
                    moneda = 0.2535;
                    result = monto * moneda;
                    break;
                case "Libra Esterlina":
                    moneda = 0.2167;
                    result = monto * moneda;
                    break;
                case "Yen Japones":
                    moneda = 39.8045;
                    result = monto * moneda;
                    break;
                case "Won Sur Coreano":
                    moneda = 0.0028;
                    result = monto * moneda;
                    break;

            }
        }

    }

}
